env:
  - RUST_BACKTRACE=full
  - DISPLAY=:99.0
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libx11-xcb-dev; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install xorg-dev; fi
before_script:
  - if [ $TRAVIS_OS_NAME = linux ]; then "sh -e /etc/init.d/xvfb start"; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sleep 3; fi
language: rust
rust:
  - stable
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
  fast_finish: true
cache: cargo
script:
  - cargo build --verbose
  - cargo test

