env:
  - RUST_BACKTRACE=full
before_install:
  - sudo apt-get install xorg-dev
language: rust
rust:
  - stable
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
  fast_finish: true
cache: cargo
script:
  - cargo build --verbose
  - cargo test

