env:
  - RUST_BACKTRACE=full
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install xorg-dev; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libx11-xcb-dev; fi
language: rust
rust:
  - stable
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
  fast_finish: true
cache: cargo
script:
  - if [ $TRAVIS_OS_NAME = linux ]; then "xvfb-run --server-args='-screen 0 1024x768x24'"; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sleep 3; fi
  - cargo build --verbose
  - cargo test

