env:
  - RUST_BACKTRACE=full
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libx11-xcb-dev; fi

language: rust
rust:
  - stable
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
  fast_finish: true
cache: cargo
script:
  - cargo build --verbose
  - cargo test

